version: '2'
services:
  app:
    container_name: evote-pemira
    image: yiisoftware/yii2-php:8.1-fpm-nginx
    restart: always
    volumes:
      - .:/app
      - /home/zhakys/Documents/project/devs:/devs
    ports:
      - '80:80'
      - '127.0.0.1:443:443'
    environment:
      - PHP_ENABLE_XDEBUG=1
    networks:
      - internal-network
  db:
    container_name: evote-pemira-db
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_DATABASE=evote-pemira-db
      - MARIADB_ROOT_PASSWORD=3210cacad
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - internal-network


networks:
  internal-network:
    driver: bridge

volumes:
  mariadb: